#include "HBC_MISC.h"
#include "Flash.h"
#include "EEPROM_POS.h"
extern ALARM_Str ALARM1,ALARM2,ALARM3;
extern u16 wdt;
extern u8 screen_auto;
extern u8 screen_br;
void Delay(uint32_t nCount)
{
  for(; nCount != 0; nCount--);
}	
void Storage_Get(void){
	u16 buf;
	wdt=FLASH_ReadHalfWord(FLASH_SAVE_ADDR+WDT_ADDR);
	buf=FLASH_ReadHalfWord(FLASH_SAVE_ADDR+SCREENSET_ADDR);
	screen_br=buf&0xFF;
	screen_auto=(buf&0x100)==0x100;
	ALARM1.ALARM_CTL=FLASH_ReadHalfWord(FLASH_SAVE_ADDR+ALARM1_ADDR);
	ALARM1.ALARM_HOUR=FLASH_ReadHalfWord(FLASH_SAVE_ADDR+ALARM1_ADDR+2);
	ALARM1.ALARM_MINUTE=FLASH_ReadHalfWord(FLASH_SAVE_ADDR+ALARM1_ADDR+4);
	
	ALARM2.ALARM_CTL=FLASH_ReadHalfWord(FLASH_SAVE_ADDR+ALARM2_ADDR);
	ALARM2.ALARM_HOUR=FLASH_ReadHalfWord(FLASH_SAVE_ADDR+ALARM2_ADDR+2);
	ALARM2.ALARM_MINUTE=FLASH_ReadHalfWord(FLASH_SAVE_ADDR+ALARM2_ADDR+4);
	
	ALARM3.ALARM_CTL=FLASH_ReadHalfWord(FLASH_SAVE_ADDR+ALARM3_ADDR);
	ALARM3.ALARM_HOUR=FLASH_ReadHalfWord(FLASH_SAVE_ADDR+ALARM3_ADDR+2);
	ALARM3.ALARM_MINUTE=FLASH_ReadHalfWord(FLASH_SAVE_ADDR+ALARM3_ADDR+4);

}

void Storage_Set(void){
	u16 buf;
	buf=screen_br;
	buf|=screen_auto<<8;
	FLASH_Erase(FLASH_SAVE_ADDR);
	FLASH_WriteData(FLASH_SAVE_ADDR+SCREENSET_ADDR,buf);
	FLASH_WriteData(FLASH_SAVE_ADDR+WDT_ADDR,wdt);
	FLASH_WriteData(FLASH_SAVE_ADDR+ALARM1_ADDR,ALARM1.ALARM_CTL);
	FLASH_WriteData(FLASH_SAVE_ADDR+ALARM1_ADDR+2,ALARM1.ALARM_HOUR);
	FLASH_WriteData(FLASH_SAVE_ADDR+ALARM1_ADDR+4,ALARM1.ALARM_MINUTE);
	
	FLASH_WriteData(FLASH_SAVE_ADDR+ALARM2_ADDR,ALARM2.ALARM_CTL);
	FLASH_WriteData(FLASH_SAVE_ADDR+ALARM2_ADDR+2,ALARM2.ALARM_HOUR);
	FLASH_WriteData(FLASH_SAVE_ADDR+ALARM2_ADDR+4,ALARM2.ALARM_MINUTE);
	
	FLASH_WriteData(FLASH_SAVE_ADDR+ALARM3_ADDR,ALARM3.ALARM_CTL);
	FLASH_WriteData(FLASH_SAVE_ADDR+ALARM3_ADDR+2,ALARM3.ALARM_HOUR);
	FLASH_WriteData(FLASH_SAVE_ADDR+ALARM3_ADDR+4,ALARM3.ALARM_MINUTE);

}
